# Generated by Django 4.2.6 on 2023-11-06 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='useername',
            new_name='username',
        ),
    ]
